stages: [test]

variables:
  BASE_URL: "http://localhost:3000"
  HEADLESS: "true"

e2e_selenium:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  before_script:
    - apt-get update && apt-get install -y chromium ca-certificates unzip curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs
    - node -v && npm -v
    - npm ci
    - npm run build
    - nohup npm start -- -p 3000 &
    - for i in {1..60}; do curl -fsS http://localhost:3000 && break || echo "Esperando app..."; sleep 2; done
  script:
    - cd qa/selenium
    - mvn -q -Dtest='*Smoke*' test
  artifacts:
    when: always
    paths:
      - qa/selenium/target/surefire-reports
    expire_in: 7 days
