# docker-compose.yml
services:
  web:
    image: node:20-alpine
    container_name: dmh-web-dev
    working_dir: /app
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.local               # <-- pon aquí tus NEXT_PUBLIC_...
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    command: sh -lc "test -x node_modules/.bin/next || npm ci --prefer-offline --no-audit --fund=false;
      npm run dev"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request({host:'localhost',port:3000,path:'/'},r=>process.exit(r.statusCode?0:1)).on('error',()=>process.exit(1)).end()"]
      interval: 10s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: dmh-mailhog
    ports:
      - "8025:8025"
    restart: unless-stopped

volumes:
  node_modules:
